import {chromium} from 'playwright';
import assert from 'node:assert/strict';
const threadUrl = process.env.BB_TEST_THREAD_URL;
if (!threadUrl) throw new Error('Set BB_TEST_THREAD_URL to a manually selected model thread in your local BB.');
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH??'/usr/bin/chromium'});
const page=await browser.newPage({viewport:{width:1280,height:900}});
page.on('pageerror',e=>console.log('PAGE ERROR',e.message));
await page.goto(new URL(threadUrl).origin);
await page.goto(threadUrl);
await page.getByRole('button',{name:'Conversation space',exact:true}).waitFor({timeout:20000});
await page.waitForTimeout(1500);
assert.equal(await page.locator('[data-jev-route-badge]').count(),0);
await page.getByRole('button',{name:'Conversation space',exact:true}).click();
const dialog=page.getByRole('dialog',{name:'Conversation space',exact:true});
await dialog.waitFor();
console.log(await dialog.innerText());
await page.screenshot({path:'docs/media/conversation-space-live.png'});
await dialog.getByText('View details').click();
const session=page.getByRole('dialog',{name:'Session usage',exact:true});await session.waitFor();
assert.match(await session.innerText(),/Raw message data/);
await page.keyboard.press('Escape');
await session.waitFor({state:'hidden'});
await dialog.waitFor({state:'hidden'});
console.log('PASS live popover, details, Escape, manual-model badge hidden; URL',page.url());
await page.route('**/api/v1/plugins/jev-route/rpc/latest', route=>route.fulfill({json:{ok:true,result:{route:{at:new Date().toISOString(),model:'gpt-6-sol',effort:'high'},previousModel:'gpt-6-luna',execution:{model:'jev/auto',providerId:'codex',reasoningLevel:'',at:Date.now()},switches:[],display:{showThreadRoute:true,showSwitchHistory:true}}}}));
const picker=page.locator('button[aria-label^="Provider, model and reasoning"]').first();
await picker.evaluate(button=>{button.textContent='Jev Routing';});
await page.locator('[data-jev-route-badge]').waitFor({timeout:10000});
await page.locator('[data-jev-route-badge]').click();
await page.locator('[data-jev-switch-history][open]').waitFor();
await picker.evaluate(button=>{button.textContent='GPT-6 Astra';});
await page.locator('[data-jev-route-badge]').waitFor({state:'detached'});
await page.locator('[data-jev-switch-history]').waitFor({state:'detached'});
console.log('PASS Jev badge and history disappear immediately when selecting a manual model (fixture route)');
await page.setViewportSize({width:390,height:844});
await page.evaluate(()=>document.documentElement.classList.add('dark'));
await page.getByRole('button',{name:'Conversation space',exact:true}).click();
assert.ok((await dialog.boundingBox()).width<=390);
await page.screenshot({path:'docs/media/conversation-space-mobile.png'});
await browser.close();
