import assert from "node:assert/strict";
import test from "node:test";
import { emptyDocument,createNode,connect,groupNodes,extractEnsemble,placeEnsemble,removeNodes,setPresentation,moveNodes,arrange,documentSchema,importDocument,exportDocument,commit,undo,redo } from "./document.ts";
const fixture=()=>{const a=createNode("note","project",{x:60,y:120,w:300,h:200}),b=createNode("text","project",{x:430,y:140,w:200,h:180});let d={...emptyDocument(),nodes:[a,b]};d=connect(d,a.id,b.id);d=groupNodes(d,[a.id,b.id]);return {d,a,b,boxes:new Map(d.nodes.map(n=>[n.id,n.box]))};};
test("ensemble placement remaps groups and cables without copying a live session",()=>{
 const {d,a,b,boxes}=fixture();const role={id:"review",name:"Reviewer",color:"#578af3",instructions:"Review",maestro:false};let source={...d,roles:[role]};source=setPresentation(source,"live",{box:{x:80,y:80,w:540,h:420},roleId:role.id});source=connect(source,"live",a.id);boxes.set("live",source.presentations.live.box!);
 const ensemble=extractEnsemble(source,[a.id,b.id,"live"],boxes,new Map([["live","Agent"]]));const placed=placeEnsemble(source,ensemble,"other","floor",800,400);assert.ok(documentSchema.safeParse(placed.document).success);const copies=placed.document.nodes.filter(n=>placed.ids.includes(n.id));assert.equal(copies.length,3);assert.ok(copies.every(n=>n.workspaceId==="other"&&n.environmentId==="floor"&&n.threadId===null));assert.equal(copies.find(n=>n.title==="Agent")!.roleId,role.id);assert.equal(placed.document.edges.filter(e=>placed.ids.includes(e.source)&&placed.ids.includes(e.target)).length,2);assert.equal(placed.document.groups.at(-1)!.members.length,2);assert.deepEqual(d.nodes[0].box,{x:60,y:120,w:300,h:200});
});
test("locks survive move and alignment; deletion removes graph and collection references",()=>{let {d,a,b,boxes}=fixture();d=setPresentation(d,a.id,{locked:true});const moved=moveNodes(d,[a.id,b.id],21,39,boxes,true);assert.deepEqual(moved.nodes[0].box,a.box);assert.equal(moved.nodes[1].box.x,460);assert.deepEqual(arrange(moved,[a.id,b.id],boxes,"left").nodes[0].box,a.box);d={...d,collections:[{id:"collection",title:"Notes",members:[a.id]}]};const removed=removeNodes(d,[a.id]);assert.equal(removed.edges.length,0);assert.equal(removed.groups.length,0);assert.deepEqual(removed.collections[0].members,[]);assert.ok(documentSchema.safeParse(removed).success);});
test("imports reject duplicate cables, ambiguous ensemble groups and unknown live roles",()=>{const {d,a,b}=fixture();assert.deepEqual(importDocument(exportDocument(d)),d);assert.throws(()=>importDocument(JSON.stringify({...d,edges:[...d.edges,{id:"duplicate",source:b.id,target:a.id}]})));assert.throws(()=>importDocument(JSON.stringify({...d,presentations:{live:{roleId:"missing",locked:false,blurred:false}}})));const ensemble=extractEnsemble(d,[a.id,b.id],new Map(d.nodes.map(n=>[n.id,n.box])));ensemble.groups.push({...ensemble.groups[0],id:"second"});assert.throws(()=>importDocument(JSON.stringify({...d,ensembles:[ensemble]})));assert.throws(()=>importDocument(" ".repeat(5000001)));});
test("undo and redo restore complete document transactions and new edits discard redo",()=>{const {d,a}=fixture();let h={past:[],present:emptyDocument(),future:[]} as Parameters<typeof commit>[0];h=commit(h,d);const next=removeNodes(d,[a.id]);h=commit(h,next);h=undo(h);assert.deepEqual(h.present,d);assert.deepEqual(redo(h).present,next);h=commit(h,{...d,nodes:d.nodes.map(n=>({...n,title:"Changed"}))});assert.equal(h.future.length,0);assert.deepEqual(undo(h).present,d);});
