import { useEffect,useLayoutEffect,useMemo,useRef,useState,type CSSProperties,type PointerEvent as ReactPointerEvent } from "react";
import { ThreadChat,Markdown,experimental_Icon as Icon,experimental_NewThreadComposer as NewThreadComposer,useSdk,useRpc,useRealtime,useBbNavigate,type NewThreadRequest } from "@get-bb/plugin-sdk/app";
import { type Snapshot,type rpcContract } from "./contract";
import { workspaceLayout,browserNodeId,edgePath,type Box } from "./graph";
import { useCanvasNavigation } from "./navigation";
import { uiMessageSchema } from "./control";
import { readState } from "./lib_state";
import { BrowserPreview } from "./surfaces";
import {exportLibrary,importLibrary,placeCollection} from "./library";
import {ThreadTerminal} from "./terminal";
import {Portal} from "./portal";
import {Routines} from "./routines-ui";
import {useHostWorkspaces,FloorReview} from "./host-surfaces";
import { emptyDocument,readDocument,writeDocument,createNode,newId,presentation,setPresentation,moveNodes,removeNodes,connect,groupNodes,ungroupNodes,bounds,arrange,magneticBox,extractEnsemble,placeEnsemble,importDocument,exportDocument,commit,undo,redo,snap,boundedBox,type CanvasDocument,type CanvasNode,type History,type Arrangement } from "./document";
import "./workbench.css";
const ORIGIN=120000;
const stacked=()=>window.matchMedia("(max-width:600px)").matches;
const stateNames={working:"Working",waiting:"Needs you",failed:"Failed",completed:"Done",idle:"Idle"};
type Tool="select"|"pan"|"connect"|CanvasNode["kind"];
type Item={id:string;title:string;box:Box;workspaceId:string;environmentId:string|null;kind:CanvasNode["kind"]|"browser";thread?:Snapshot["threads"][number];browser?:Snapshot["browsers"][number];node?:CanvasNode};
const tools:[Tool,string,string][]=[["select","MousePointer2","Select"],["agent","Terminal","Agent"],["note","StickyNote","Note"],["connect","Link","Connect"],["files","Folder","File tree"],["text","Type","Text"],["drawing","Pencil","Drawing"],["portal","Globe","Portal"]];
const editable=(t:EventTarget|null)=>t instanceof HTMLElement&&Boolean(t.closest("input,textarea,select,[contenteditable=true],.native-chat"));
export function Workbench({snapshot,refresh}:{snapshot:Snapshot;refresh:()=>void}){
 const rpc=useRpc<typeof rpcContract>(),sdk=useSdk(),navigate=useBbNavigate();
 const host=useHostWorkspaces(snapshot.capturedAt);
 const [history,setHistory]=useState<History>(()=>({past:[],present:readDocument(),future:[]}));const d=history.present,dRef=useRef(d);dRef.current=d;
 const [project,setProject]=useState<string|null>(null),[environment,setEnvironment]=useState<string|null>(null),[tool,setTool]=useState<Tool>("select"),[selection,setSelection]=useState<string[]>([]),[zoom,setZoom]=useState(1),[drawer,setDrawer]=useState<string|null>(null),[query,setQuery]=useState(""),[notice,setNotice]=useState("");
 const [preview,setPreview]=useState<CanvasDocument|null>(null),[marquee,setMarquee]=useState<Box|null>(null),[lifted,setLifted]=useState<{id:string;dock:"left"|"right"|null}|null>(null),[mapOpen,setMapOpen]=useState(false),[agentRole,setAgentRole]=useState<string>(""),[spawnTarget,setSpawnTarget]=useState<CanvasNode|null>(null),[recruitParent,setRecruitParent]=useState<string|null>(null);
 const canvas=useRef<HTMLDivElement>(null),zoomTo=useCanvasNavigation(canvas,zoom,setZoom),space=useRef(false),gesture=useRef<null|{kind:"move"|"resize"|"pan"|"insert"|"marquee";sx:number;sy:number;point:{x:number;y:number};document:CanvasDocument;boxes:Map<string,Box>;ids:string[];left:number;top:number;alt:boolean;tool:Tool}>(null);
 const [viewport,setViewport]=useState({x:0,y:0,w:1000,h:700});const clipboard=useRef<ReturnType<typeof extractEnsemble>|null>(null),suppressClick=useRef(false),returnFocus=useRef<HTMLElement|null>(null),drawerRef=useRef<HTMLElement>(null),clientId=useRef(`canvas-${newId()}`);
 const document=preview??d;
 const spatial=useMemo(()=>workspaceLayout(snapshot.threads,snapshot.browsers),[snapshot]);
 const projects=useMemo(()=>Array.from(new Map([...host.projects.map(p=>[p.id,p.name] as const),...snapshot.threads.map(t=>[t.projectId,t.project] as const),...d.nodes.map(n=>[n.workspaceId,snapshot.threads.find(t=>t.projectId===n.workspaceId)?.project??"Saved workspace"] as const)]),([id,name])=>({id,name})),[snapshot,d.nodes,host.projects]);
 const workspaceId=project??projects[0]?.id??"personal";
 const allItems=useMemo(()=>{
  const legacy=readState("global");
  const live:Item[]=snapshot.threads.map(t=>{const group=spatial.groups.find(g=>g.nodeIds.includes(t.id));const old=legacy.panes[t.id];const original=old&&group?{...old,x:old.x+group.x,y:old.y+group.y}:spatial.nodes.get(t.id)??{x:40,y:100,w:540,h:420};return {id:t.id,title:t.title,box:document.presentations[t.id]?.box??original,workspaceId:t.projectId,environmentId:t.environmentId,kind:"agent",thread:t};});
  const browsers:Item[]=snapshot.browsers.map(b=>{const id=browserNodeId(b),t=snapshot.threads.find(t=>t.id===b.threadId);return {id,title:b.title,box:document.presentations[id]?.box??spatial.nodes.get(id)??{x:40,y:100,w:540,h:420},workspaceId:t?.projectId??workspaceId,environmentId:b.environmentId,kind:"browser",browser:b};});
  return [...live,...browsers,...document.nodes.filter(n=>!n.threadId||!live.some(t=>t.id===n.threadId)).map(n=>({id:n.id,title:n.title,box:n.box,workspaceId:n.workspaceId,environmentId:n.environmentId,kind:n.kind,node:n} as Item))];
 },[snapshot,spatial,document,workspaceId]);
 const items=allItems.filter(i=>(!project||i.workspaceId===project)&&(!environment||i.environmentId===environment));const boxes=useMemo(()=>new Map(allItems.map(i=>[i.id,i.box])),[allItems]);const frame=bounds(items.map(i=>i.box))??{x:0,y:0,w:1000,h:700};
 const currentSelection=selection.filter(id=>items.some(i=>i.id===id));
 function update(next:CanvasDocument|((d:CanvasDocument)=>CanvasDocument)){try{setHistory(h=>commit(h,typeof next==="function"?next(h.present):next));}catch(e){setNotice(e instanceof Error?e.message:"Canvas change failed");}}
 function open(name:string){returnFocus.current=documentElement();setDrawer(name);setQuery("");}
 function documentElement(){return window.document.activeElement instanceof HTMLElement?window.document.activeElement:null;}
 function close(){setDrawer(null);setSpawnTarget(null);setRecruitParent(null);returnFocus.current?.focus();}
 function updateNode(id:string,patch:Partial<CanvasNode>){update(v=>({...v,nodes:v.nodes.map(n=>n.id===id?{...n,...patch}:n)}));}
 useEffect(()=>{try{writeDocument(d);setNotice(n=>n.startsWith("Save failed")?"":n);}catch{setNotice("Save failed. Your changes remain in this view. Export a backup or retry.");}},[d]);
 useEffect(()=>{if(!drawer)return;const el=drawerRef.current;el?.querySelector<HTMLElement>("input,button,textarea")?.focus();},[drawer]);
 useEffect(()=>{const down=(e:KeyboardEvent)=>{if(e.code==="Space"&&!editable(e.target)&&!(e.target instanceof HTMLElement&&e.target.closest("button,a"))){space.current=true;e.preventDefault();}};const up=()=>{space.current=false;};window.addEventListener("keydown",down);window.addEventListener("keyup",up);window.addEventListener("blur",up);return()=>{window.removeEventListener("keydown",down);window.removeEventListener("keyup",up);window.removeEventListener("blur",up);};},[]);
 const [sharedReady,setSharedReady]=useState(false),[saveState,setSaveState]=useState<"saved"|"saving"|"error">("saved");
 const [saveTick,setSaveTick]=useState(0);
 const sharedRevision=useRef(0),sharedSaving=useRef(false),lastShared=useRef("");
 useEffect(()=>{let disposed=false;void rpc.call("readDocument",null).then(value=>{if(disposed)return;sharedRevision.current=value.revision;if(value.revision>0){try{localStorage.setItem("agent-canvas:document:pre-shared-backup",exportDocument(dRef.current));}catch{/* preserve current in memory */}setHistory({past:[],present:value.document,future:[]});lastShared.current=JSON.stringify(value.document);}setSharedReady(true);}).catch(()=>{if(!disposed){setNotice("Shared canvas unavailable. Local drafts are retained; reload the shared canvas when connected.");setSaveState("error");}});return()=>{disposed=true;};},[rpc]);
 useEffect(()=>{if(!sharedReady)return;const serialized=JSON.stringify(d);if(serialized===lastShared.current)return;const timer=setTimeout(()=>{if(sharedSaving.current)return;sharedSaving.current=true;setSaveState("saving");void rpc.call("saveDocument",{revision:sharedRevision.current,document:d}).then(value=>{sharedRevision.current=value.revision;lastShared.current=serialized;setSaveState("saved");setSaveTick(v=>v+1);}).catch(e=>{setSaveState("error");setNotice(e instanceof Error?e.message:"Shared save failed. Your local draft is retained.");}).finally(()=>{sharedSaving.current=false;});},600);return()=>clearTimeout(timer);},[d,sharedReady,rpc,saveTick]);
 useRealtime("document-changed",raw=>{const revision=(raw as {revision?:number})?.revision;if(typeof revision!=="number"||revision<=sharedRevision.current||sharedSaving.current)return;if(JSON.stringify(dRef.current)!==lastShared.current){setSaveState("error");setNotice("Shared canvas changed while you were editing. Export your local draft before reloading the shared canvas.");return;}void rpc.call("readDocument",null).then(value=>{sharedRevision.current=value.revision;lastShared.current=JSON.stringify(value.document);setHistory({past:[],present:value.document,future:[]});}).catch(()=>setNotice("Could not refresh shared canvas."));});
 async function reloadShared(){try{const value=await rpc.call("readDocument",null);localStorage.setItem("agent-canvas:document:conflict-backup",exportDocument(dRef.current));sharedRevision.current=value.revision;lastShared.current=JSON.stringify(value.document);setHistory({past:[],present:value.document,future:[]});setSharedReady(true);setSaveState("saved");setNotice("Shared canvas reloaded. Previous local draft is backed up.");}catch{setNotice("Shared canvas is still unavailable; your draft remains local.");}}
 const pendingFocus=useRef<string|null>(null);
 useLayoutEffect(()=>{
  const el=canvas.current;if(!el)return;const media=window.matchMedia("(max-width:600px)");
  let frame:number|undefined;
  const restore=()=>{if(media.matches){el.scrollTo(0,0);return;}const view=dRef.current.viewports[project??"all"];zoomTo(view?.zoom??1,false);frame=requestAnimationFrame(()=>el.scrollTo((ORIGIN+(view?.x??0))*(view?.zoom??1),(ORIGIN+(view?.y??0))*(view?.zoom??1)));};
  if(!pendingFocus.current){setEnvironment(dRef.current.viewports[project??"all"]?.environmentId??null);restore();}
  media.addEventListener("change",restore);return()=>{media.removeEventListener("change",restore);if(frame!==undefined)cancelAnimationFrame(frame);};
 },[project,sharedReady]);
 function onScroll(){const el=canvas.current;if(!el)return;if(stacked()){const view=dRef.current.viewports[project??"all"];setViewport({x:view?.x??0,y:view?.y??0,w:el.clientWidth,h:el.clientHeight});}else setViewport({x:el.scrollLeft/zoom-ORIGIN,y:el.scrollTop/zoom-ORIGIN,w:el.clientWidth/zoom,h:el.clientHeight/zoom});}
 useEffect(()=>{onScroll();const el=canvas.current;if(!el)return;const ro=new ResizeObserver(onScroll);ro.observe(el);return()=>ro.disconnect();},[zoom,project]);
 useEffect(()=>{if(stacked()||!sharedReady)return;const timer=setTimeout(()=>{if(stacked())return;setHistory(h=>({...h,present:{...h.present,viewports:{...h.present.viewports,[project??"all"]:{x:Math.max(-100000,Math.min(100000,viewport.x)),y:Math.max(-100000,Math.min(100000,viewport.y)),zoom,environmentId:environment}}}}));},500);return()=>clearTimeout(timer);},[viewport.x,viewport.y,zoom,environment,project,sharedReady]);
 function focus(id:string){const item=allItems.find(i=>i.id===id);if(!item||!canvas.current)return false;pendingFocus.current=id;setProject(item.workspaceId);setEnvironment(item.environmentId);setSelection([id]);return true;}
 useEffect(()=>{const id=pendingFocus.current;if(!id)return;const item=allItems.find(i=>i.id===id),el=canvas.current;if(!item||!el)return;pendingFocus.current=null;const frame=requestAnimationFrame(()=>{if(stacked()){Array.from(el.querySelectorAll<HTMLElement>("[data-node-id]")).find(n=>n.dataset.nodeId===id)?.scrollIntoView({block:"center",behavior:"smooth"});}else{const b=item.box;el.scrollTo({left:(ORIGIN+b.x+b.w/2)*zoom-el.clientWidth/2,top:(ORIGIN+b.y+b.h/2)*zoom-el.clientHeight/2,behavior:"smooth"});}});return()=>cancelAnimationFrame(frame);},[selection,project,environment,zoom,allItems]);
 function fit(ids?:string[]){const el=canvas.current;if(!el)return;if(stacked()){if(ids?.length)focus(ids[0]);else el.scrollTo(0,0);return;}const b=bounds((ids?allItems.filter(i=>ids.includes(i.id)):items).map(i=>i.box));if(!b)return;const z=Math.max(.1,Math.min(1.5,Math.min((el.clientWidth-100)/Math.max(b.w,1),(el.clientHeight-140)/Math.max(b.h,1))));zoomTo(z,false);requestAnimationFrame(()=>el.scrollTo((ORIGIN+b.x+b.w/2)*z-el.clientWidth/2,(ORIGIN+b.y+b.h/2)*z-el.clientHeight/2));}
 function point(e:{clientX:number;clientY:number}){const el=canvas.current!,r=el.getBoundingClientRect();return stacked()?{x:viewport.x+40,y:viewport.y+80}:{x:(e.clientX-r.left+el.scrollLeft)/zoom-ORIGIN,y:(e.clientY-r.top+el.scrollTop)/zoom-ORIGIN};}

 function start(e:ReactPointerEvent,item?:Item,mode:"move"|"resize"="move"){
  if(e.button!==0&&e.button!==1)return;if(editable(e.target)&&!space.current&&e.button!==1)return;
  const el=canvas.current;if(!el)return;const pan=e.button===1||space.current||tool==="pan";
  if(!pan&&(e.target as HTMLElement).closest("button,input,textarea,select,a,.native-chat,.drawing-surface"))return;
  if(!pan&&item&&presentation(d,item.id).locked){setSelection([item.id]);return;}
  e.preventDefault();e.stopPropagation();el.focus({preventScroll:true});
  const p=point(e);let ids=item?(selection.includes(item.id)?selection:[item.id]):[];
  if(item&&!pan&&e.shiftKey)return;
  if(item&&!pan&&tool==="connect"){suppressClick.current=true;if(selection[0]&&selection[0]!==item.id){update(v=>connect(v,selection[0],item.id));setTool("select");}setSelection([item.id]);return;}
  let source=d;
  if(item&&!pan&&e.altKey){const result=placeEnsemble(d,extractEnsemble(d,ids,boxes,new Map(allItems.map(i=>[i.id,i.title]))),workspaceId,environment,bounds(ids.map(id=>boxes.get(id)!))!.x,bounds(ids.map(id=>boxes.get(id)!))!.y);source=result.document;ids=result.ids;}
  if(item&&!pan){setSelection(ids);suppressClick.current=true;}
  const kind=pan?"pan":item?mode:tool!=="select"&&tool!=="connect"?"insert":"marquee";
  gesture.current={kind,sx:e.clientX,sy:e.clientY,point:p,document:source,boxes:new Map([...boxes,...source.nodes.map(n=>[n.id,n.box] as const)]),ids,left:el.scrollLeft,top:el.scrollTop,alt:e.altKey,tool};
  if(kind==="marquee"){if(!e.shiftKey)setSelection([]);setMarquee({x:p.x,y:p.y,w:0,h:0});}
 }
 useEffect(()=>{
  const move=(e:PointerEvent)=>{const g=gesture.current,el=canvas.current;if(!g||!el)return;const dx=(e.clientX-g.sx)/zoom,dy=(e.clientY-g.sy)/zoom;
   if(g.kind==="pan"){el.scrollTo(g.left-(e.clientX-g.sx),g.top-(e.clientY-g.sy));return;}
   if(g.kind==="marquee"||g.kind==="insert"){setMarquee({x:Math.min(g.point.x,g.point.x+dx),y:Math.min(g.point.y,g.point.y+dy),w:Math.abs(dx),h:Math.abs(dy)});return;}
   let next=g.document;
   if(g.kind==="move"){next=moveNodes(next,g.ids,dx,dy,g.boxes,d.settings.grid);if(e.ctrlKey){for(const id of g.ids){const b=next.nodes.find(n=>n.id===id)?.box??next.presentations[id]?.box;if(b)next=setPresentation(next,id,{box:magneticBox(b,[...g.boxes].filter(([key])=>!g.ids.includes(key)).map(([,v])=>v))});}}}
   else for(const id of g.ids){const b=g.boxes.get(id);if(b&&!presentation(g.document,id).locked)next=setPresentation(next,id,{box:boundedBox({...b,w:snap(b.w+dx),h:snap(b.h+dy)})});}
   setPreview(next);
  };
  const up=(e:PointerEvent)=>{const g=gesture.current;if(!g)return;gesture.current=null;const dx=(e.clientX-g.sx)/zoom,dy=(e.clientY-g.sy)/zoom;
   if(g.kind==="move"||g.kind==="resize"){if(preview)update(preview);else if(g.alt)update(g.document);}
   if(g.kind==="marquee"){const b={x:Math.min(g.point.x,g.point.x+dx),y:Math.min(g.point.y,g.point.y+dy),w:Math.abs(dx),h:Math.abs(dy)};setSelection(items.filter(i=>i.box.x<=b.x+b.w&&i.box.x+i.box.w>=b.x&&i.box.y<=b.y+b.h&&i.box.y+i.box.h>=b.y).map(i=>i.id));}
   if(g.kind==="insert"){const kind=g.tool as CanvasNode["kind"],b={x:snap(Math.min(g.point.x,g.point.x+dx)),y:snap(Math.min(g.point.y,g.point.y+dy)),w:snap(Math.abs(dx)>20?Math.abs(dx):kind==="note"?d.settings.noteWidth:d.settings.nodeWidth),h:snap(Math.abs(dy)>20?Math.abs(dy):kind==="note"?d.settings.noteHeight:d.settings.nodeHeight)};const node=createNode(kind,workspaceId,b,environment);if(kind==="agent"){setSpawnTarget(node);open("agent");}else{update(v=>({...v,nodes:[...v.nodes,node]}));setSelection([node.id]);}setTool("select");}
   setPreview(null);setMarquee(null);setTimeout(()=>{suppressClick.current=false;},0);
  };
  const cancel=()=>{gesture.current=null;setPreview(null);setMarquee(null);};window.addEventListener("pointermove",move);window.addEventListener("pointerup",up);window.addEventListener("pointercancel",cancel);return()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",up);window.removeEventListener("pointercancel",cancel);};
 },[zoom,preview,items,d,environment,workspaceId]);
 function duplicate(){const e=extractEnsemble(d,currentSelection,boxes,new Map(allItems.map(i=>[i.id,i.title])));const result=placeEnsemble(d,e,workspaceId,environment,(bounds(currentSelection.map(id=>boxes.get(id)!))?.x??0)+40,(bounds(currentSelection.map(id=>boxes.get(id)!))?.y??0)+40);update(result.document);setSelection(result.ids);}
 function saveEnsemble(){const e=extractEnsemble(d,currentSelection,boxes,new Map(allItems.map(i=>[i.id,i.title])));e.title=`Ensemble ${d.ensembles.length+1}`;update({...d,ensembles:[...d.ensembles,e]});open("ensembles");}
 function deleteSelection(){const authored=currentSelection.filter(id=>d.nodes.some(n=>n.id===id));if(authored.length)update(removeNodes(d,authored));setSelection([]);if(authored.length!==currentSelection.length)setNotice("Live conversations stay in BB. Use their native thread actions to stop or archive them.");}
 function downloadData(data:string,name:string){const blob=new Blob([data],{type:"application/json"}),url=URL.createObjectURL(blob),a=window.document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function download(){downloadData(exportDocument(d),"agent-canvas.json");}
 async function importLibraryFile(file:File){try{if(file.size>2_000_000)throw Error("Library import exceeds 2 MB");update(importLibrary(d,await file.text()));setNotice("Library imported. Place a composition, then launch agents explicitly.");}catch(e){setNotice(e instanceof Error?e.message:"Library import failed");}}
 async function importFile(file:File){try{if(file.size>5_000_000)throw Error("Canvas import exceeds 5 MB");const next=importDocument(await file.text());update(next);setSelection([]);setNotice("Canvas imported. Agent templates require an explicit launch.");}catch(e){setNotice(e instanceof Error?e.message:"Import failed");}}
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(editable(e.target)&&!drawer)return;if(e.key==="Escape"){if(drawer)close();else{setTool("select");setLifted(null);setSelection([]);}return;}if(editable(e.target))return;const mod=e.ctrlKey||e.metaKey;if(mod&&e.key.toLowerCase()==="k"){e.preventDefault();open("search");return;}if(mod&&e.key.toLowerCase()==="z"){e.preventDefault();setHistory(h=>e.shiftKey?redo(h):undo(h));return;}if(mod&&e.key.toLowerCase()==="g"){e.preventDefault();update(e.shiftKey?ungroupNodes(d,currentSelection):groupNodes(d,currentSelection));return;}if(mod&&e.key.toLowerCase()==="c"&&currentSelection.length){e.preventDefault();clipboard.current=extractEnsemble(d,currentSelection,boxes,new Map(allItems.map(i=>[i.id,i.title])));return;}if(mod&&e.key.toLowerCase()==="v"&&clipboard.current){e.preventDefault();const r=placeEnsemble(d,clipboard.current,workspaceId,environment,viewport.x+80,viewport.y+100);update(r.document);setSelection(r.ids);return;}if(mod&&e.shiftKey&&e.key.toLowerCase()==="m"){e.preventDefault();setMapOpen(v=>!v);return;}if(mod&&e.shiftKey&&e.key.toLowerCase()==="a"){e.preventDefault();const candidates=allItems.filter(i=>i.thread?.state==="waiting").sort((a,b)=>a.id.localeCompare(b.id));const ix=candidates.findIndex(i=>i.id===selection[0]);if(candidates.length)focus(candidates[(ix+1)%candidates.length].id);return;}if(mod&&e.altKey&&(e.key==="ArrowRight"||e.key==="ArrowLeft")){e.preventDefault();const links=[...d.edges,...snapshot.threads.filter(t=>t.parentThreadId).map(t=>({id:t.id,source:t.parentThreadId!,target:t.id}))];const next=links.flatMap(l=>l.source===selection[0]?[l.target]:l.target===selection[0]?[l.source]:[]).sort();if(next.length)focus(e.key==="ArrowRight"?next[0]:next[next.length-1]);return;}if(mod&&e.key==="\\"){e.preventDefault();fit(currentSelection);return;}if(mod&&e.shiftKey&&e.key.toLowerCase()==="t"){e.preventDefault();update(arrange(d,currentSelection,boxes,"tidy"));return;}if(e.key==="Delete"||e.key==="Backspace"||(mod&&e.key.toLowerCase()==="w")){if(currentSelection.length){e.preventDefault();deleteSelection();}return;}if(e.key==="+"||e.key==="="){e.preventDefault();zoomTo(zoom+.1);}if(e.key==="-"){e.preventDefault();zoomTo(zoom-.1);}if(e.key==="0"){e.preventDefault();fit();}};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key);},[d,selection,items,allItems,boxes,drawer,zoom,viewport,workspaceId,environment]);
 useEffect(()=>{const publish=()=>void rpc.call("presence",{clientId:clientId.current,workspaceId:project,zoom,focusedThreadId:selection[0]??null,visible:window.document.visibilityState==="visible"&&window.document.hasFocus()}).catch(()=>{});publish();const timer=setInterval(publish,10000);return()=>clearInterval(timer);},[rpc,project,selection,zoom]);
 useRealtime("ui-command",raw=>{const p=uiMessageSchema.safeParse(raw);if(!p.success||p.data.clientId!==clientId.current||p.data.controlThreadId!==snapshot.controlThreadId)return;const {command,requestId}=p.data;let applied=true;if(command.action==="fit")fit();if(command.action==="zoom")zoomTo(command.value);if(command.action==="focus")applied=focus(command.threadId);if(command.action==="workspace"){applied=!command.workspaceId||projects.some(p=>p.id===command.workspaceId);if(applied){setProject(command.workspaceId);setEnvironment(null);}}if(command.action==="reorganize")update(v=>({...v,presentations:Object.fromEntries(Object.entries(v.presentations).map(([id,p])=>[id,{...p,box:undefined}]))}));void rpc.call("acknowledge",{clientId:clientId.current,requestId,applied,detail:applied?"Canvas updated.":"Requested target is unavailable."}).catch(()=>{});});
 const environments=Array.from(new Map([...host.floors.filter(f=>!project||f.projectId===project).map(f=>[f.id,`${f.name}${f.branch?` · ${f.branch}`:""}${f.status!=="ready"?` · ${f.status}`:""}`] as const),...snapshot.threads.filter(t=>!project||t.projectId===project).map(t=>[t.environmentId,t.environment] as const)]));
 const liftedItem=items.find(i=>i.id===lifted?.id);
 function selectItem(e:React.MouseEvent,id:string){if(suppressClick.current){suppressClick.current=false;return;}if(tool==="connect"){if(selection[0]&&selection[0]!==id){update(v=>connect(v,selection[0],id));setTool("select");}setSelection([id]);}else setSelection(s=>e.shiftKey?s.includes(id)?s.filter(v=>v!==id):[...s,id]:[id]);}
 function renderNode(item:Item,overlay=false){const p=presentation(document,item.id),role=document.roles.find(r=>r.id===p.roleId),active=currentSelection.includes(item.id);return <article key={item.id} data-node-id={item.id} className={`node ${item.kind==="note"?"note":""} ${active?"selected":""} ${p.locked?"locked":""} ${overlay?"lifted-node":""}`} style={{left:item.box.x,top:item.box.y,width:item.box.w,height:item.box.h,"--node-color":item.node?.color??"#78a5ed"} as CSSProperties} onClick={e=>selectItem(e,item.id)}>
  <header className="head" onPointerDown={e=>start(e,item)} onDoubleClick={()=>setLifted(l=>l?.id===item.id?null:{id:item.id,dock:null})}>
   <button className="grip" aria-label={`Move ${item.title}`} onKeyDown={e=>{const shift:{[key:string]:[number,number]}={ArrowLeft:[-20,0],ArrowRight:[20,0],ArrowUp:[0,-20],ArrowDown:[0,20]};if(shift[e.key]){e.preventDefault();update(moveNodes(d,[item.id],...shift[e.key],boxes,d.settings.grid));}}}><Icon name="GripVertical"/></button><strong className="name">{item.title}</strong>{role&&<span className="role" style={{color:role.color}}>{role.name}</span>}{item.thread&&<span className={`status ${item.thread.state}`}>{stateNames[item.thread.state]}</span>}{p.locked&&<span title="Locked">⌑</span>}<button aria-label={`Actions for ${item.title}`} onClick={e=>{e.stopPropagation();setSelection([item.id]);open("actions");}}><Icon name="MoreHorizontal"/></button>
  </header>
  {p.blurred?<button className="blur-cover" aria-label={`Reveal ${item.title}`} onClick={e=>{e.stopPropagation();update(setPresentation(d,item.id,{blurred:false}));}}><Icon name="Eye"/><span>Contents hidden</span></button>:item.thread?document.presentations[item.id]?.face==="terminal"?<ThreadTerminal threadId={item.thread.id}/>:<NativeChat threadId={item.thread.id}/>:item.browser?<div className="portal-body"><BrowserPreview browser={item.browser}/><span className="dim">Browser capture · {item.browser.location}</span><button onClick={()=>navigate.toThread(item.browser!.threadId)}>Open owning thread</button></div>:item.node?<NodeContent node={item.node} update={patch=>updateNode(item.id,patch)} onLaunch={()=>{setSpawnTarget(item.node!);setAgentRole(item.node!.roleId??"");open("agent");}}/>:null}
  <footer className="node-footer">{item.thread?`${item.thread.environment} · ${item.thread.provider}`:item.kind==="browser"?"Authorized capture":item.kind==="agent"?"Template · launch explicitly":item.kind}</footer>
  {!overlay&&<button className="resize" aria-label={`Resize ${item.title}`} onPointerDown={e=>{e.preventDefault();e.stopPropagation();if(p.locked)return;const el=canvas.current!;gesture.current={kind:"resize",sx:e.clientX,sy:e.clientY,point:point(e),document:d,boxes,ids:[item.id],left:el.scrollLeft,top:el.scrollTop,alt:false,tool};}} onKeyDown={e=>{const b={...item.box};if(e.key==="ArrowRight")b.w+=20;else if(e.key==="ArrowLeft")b.w-=20;else if(e.key==="ArrowDown")b.h+=20;else if(e.key==="ArrowUp")b.h-=20;else return;e.preventDefault();if(!p.locked)update(setPresentation(d,item.id,{box:boundedBox(b)}));}}><Icon name="Maximize2"/></button>}
 </article>;}
 return <div className="ac-workbench app"><aside className="sidebar"><div className="brand"><Icon name="Workflow"/>Agent Canvas</div><button className="sidebutton" onClick={()=>open("search")}><Icon name="Search"/>Search anything <kbd>⌘K</kbd></button><div className="label">Workspaces</div><button className={`workspace ${!project?"active":""}`} onClick={()=>{setProject(null);setEnvironment(null);}}>All workspaces</button>{projects.map((p,i)=><div key={p.id}><button className={`workspace ${project===p.id?"active":""}`} onClick={()=>{setProject(p.id);setEnvironment(null);}}><i className="swatch" style={{background:["#578af3","#ba8de0","#69baa1"][i%3]}}/>{p.name}</button>{project===p.id&&environments.filter(([id])=>id).map(([id,name])=><button key={id!} className={`floor ${environment===id?"active":""}`} onClick={()=>setEnvironment(environment===id?null:id)}><Icon name="GitBranch"/>{name}</button>)}</div>)}<button className="sidebutton" onClick={()=>open("floor")}>+ New isolated floor</button>{environment&&<button className="sidebutton" onClick={()=>open("floor-review")}>Review selected floor</button>}<div className="label">Library</div>{[["ensembles","GridView","Ensembles"],["roles","Users","Agent roles"],["collections","Notebook","Note collections"],["routines","Calendar","Routines"],["settings","Settings","Settings & shortcuts"]].map(([id,icon,title])=><button key={id} className="sidebutton" onClick={()=>open(id)}><Icon name={icon as "Settings"}/>{title}</button>)}<div className="side-foot"><span>{snapshot.threads.length} agents · {saveState==="saving"?"Saving…":saveState==="error"?"Local draft":"Saved"}</span><button onClick={refresh} aria-label="Refresh workspaces"><Icon name="RotateCcw"/></button></div></aside>
 <section className="canvas-shell"><div className="top"><span className="topname">{projects.find(p=>p.id===project)?.name??"All workspaces"}{environment?` / ${environments.find(([id])=>id===environment)?.[1]??"Floor"}`:""}</span><div className="pill">{tools.map(([id,icon,label])=><button key={id} className={`tool ${tool===id?"active":""}`} aria-label={label} title={`${label} · click or draw on canvas`} aria-pressed={tool===id} onClick={e=>{if(e.detail===0&&id!=="select"&&id!=="connect"){if(id==="agent")open("agent");else{const n=createNode(id as CanvasNode["kind"],workspaceId,{x:snap(viewport.x+80),y:snap(viewport.y+100),w:d.settings.noteWidth,h:d.settings.noteHeight},environment);update(v=>({...v,nodes:[...v.nodes,n]}));setSelection([n.id]);}setTool("select");}else setTool(id);}}><Icon name={icon as "Terminal"}/></button>)}</div></div>
 {!sharedReady&&saveState!=="error"&&<div className="sync-loading" role="status">Loading shared canvas…</div>}
 {notice&&<div className="save-notice" role="status">{notice}<button onClick={()=>{try{writeDocument(d);setNotice("");setSaveTick(v=>v+1);}catch{download();}}}>Retry / export</button><button aria-label="Dismiss notice" onClick={()=>setNotice("")}>×</button></div>}
 <div className={`canvas ${tool==="pan"?"pan-mode":""}`} ref={canvas} tabIndex={0} aria-label="Agent canvas" onScroll={onScroll} onPointerDown={e=>{if((e.target as HTMLElement).closest(".node")&&!space.current&&e.button!==1&&tool!=="pan")return;start(e);}} onPointerDownCapture={e=>{if(space.current||e.button===1||tool==="pan")start(e);}}>
  <div className="scroll-area" style={{width:(ORIGIN*2+Math.max(1000,frame.x+frame.w))*zoom,height:(ORIGIN*2+Math.max(700,frame.y+frame.h))*zoom}}><div className="world" style={{left:ORIGIN*zoom,top:ORIGIN*zoom,width:Math.max(1000,frame.x+frame.w),height:Math.max(700,frame.y+frame.h),transform:`scale(${zoom})`}}>
   {document.groups.map(g=>{const b=bounds(g.members.flatMap(id=>boxes.has(id)?[boxes.get(id)!]:[]));if(!b||!g.members.some(id=>items.some(i=>i.id===id)))return null;return <div key={g.id} className="frame" style={{left:b.x-16,top:b.y-32,width:b.w+32,height:b.h+48}}><button className="group-title" onPointerDown={e=>{const member=items.find(i=>g.members.includes(i.id));if(member){setSelection(g.members);e.preventDefault();e.stopPropagation();const el=canvas.current!;gesture.current={kind:"move",sx:e.clientX,sy:e.clientY,point:point(e),document:d,boxes,ids:g.members,left:el.scrollLeft,top:el.scrollTop,alt:false,tool};}}} onDoubleClick={()=>{setSelection(g.members);open("group");}}>{g.title}</button></div>;})}
   <svg className="links" width={Math.max(1000,frame.x+frame.w)} height={Math.max(700,frame.y+frame.h)}>{snapshot.threads.map(t=>{const a=boxes.get(t.parentThreadId??""),b=boxes.get(t.id);return a&&b&&items.some(i=>i.id===t.id)?<path className="recorded" key={`parent-${t.id}`} d={edgePath(a,b)}/>:null;})}{snapshot.browsers.map(b=>{const a=boxes.get(b.threadId),target=boxes.get(browserNodeId(b));return a&&target&&items.some(i=>i.id===browserNodeId(b))?<path className="recorded" key={browserNodeId(b)} d={edgePath(a,target)}/>:null;})}{document.edges.map(e=>{const a=boxes.get(e.source),b=boxes.get(e.target);return a&&b&&items.some(i=>[e.source,e.target].includes(i.id))?<path key={e.id} d={edgePath(a,b)}/>:null;})}</svg>
   {items.filter(i=>i.id!==lifted?.id).map(i=>renderNode(i))}{marquee&&<div className="marquee" style={{left:marquee.x,top:marquee.y,width:marquee.w,height:marquee.h}}/>}
   {!items.length&&<div className="canvas-empty" style={{left:Math.max(0,viewport.x)+80,top:Math.max(0,viewport.y)+120}}><Icon name="Workflow"/><h2>Your canvas is ready</h2><p>Add an agent, write a note, or sketch your next idea.</p><button onClick={()=>{const n=createNode("note",workspaceId,{x:viewport.x+100,y:viewport.y+100,w:320,h:300},environment);update({...d,nodes:[...d.nodes,n]});}}>Add a note</button><button onClick={()=>open("agent")}>Add an agent</button></div>}
  </div></div>
 </div>
 {liftedItem&&<div className={`lift-overlay ${lifted?.dock??"center"}`}><div className="lift-controls"><button onClick={()=>setLifted({id:liftedItem.id,dock:"left"})}>Dock left</button><button onClick={()=>setLifted({id:liftedItem.id,dock:"right"})}>Dock right</button><button onClick={()=>setLifted(null)}>Return to canvas</button></div>{renderNode(liftedItem,true)}</div>}
 {currentSelection.length>0&&<div className="selection-pill pill"><span>{currentSelection.length} selected</span><button onClick={()=>fit(currentSelection)}>Focus</button><button onClick={()=>update(groupNodes(d,currentSelection))} disabled={currentSelection.length<2}>Group</button><button onClick={()=>open("arrange")}>Arrange</button><button onClick={duplicate}>Duplicate</button><button onClick={saveEnsemble}>Save ensemble</button></div>}
 {mapOpen&&<div className="map"><svg viewBox={`${Math.min(frame.x,viewport.x)-40} ${Math.min(frame.y,viewport.y)-40} ${Math.max(frame.x+frame.w,viewport.x+viewport.w)-Math.min(frame.x,viewport.x)+80} ${Math.max(frame.y+frame.h,viewport.y+viewport.h)-Math.min(frame.y,viewport.y)+80}`} role="img" aria-label="Canvas overview" onClick={e=>{const svg=e.currentTarget,p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const matrix=svg.getScreenCTM();if(!matrix||!canvas.current)return;const q=p.matrixTransform(matrix.inverse());canvas.current.scrollTo((ORIGIN+q.x)*zoom-canvas.current.clientWidth/2,(ORIGIN+q.y)*zoom-canvas.current.clientHeight/2);}}>{items.map(i=><rect key={i.id} x={i.box.x} y={i.box.y} width={i.box.w} height={i.box.h} fill={i.kind==="note"?"#d5bc50":"#78a5ed"} fillOpacity=".4"/>)}<rect x={viewport.x} y={viewport.y} width={viewport.w} height={viewport.h} fill="none" stroke="#087ef5" strokeWidth="8"/></svg></div>}
 <div className="bottom"><div className="pill"><button aria-label="Pan canvas" aria-pressed={tool==="pan"} onClick={()=>setTool(t=>t==="pan"?"select":"pan")}><Icon name="Hand"/></button><button aria-label="Toggle minimap" aria-pressed={mapOpen} onClick={()=>setMapOpen(v=>!v)}><Icon name="Map"/></button></div><div className="pill"><button aria-label="Zoom out" onClick={()=>zoomTo(zoom-.1)}><Icon name="Minus"/></button><span>{Math.round(zoom*100)}%</span><button aria-label="Zoom in" onClick={()=>zoomTo(zoom+.1)}><Icon name="Plus"/></button><button aria-label="Fit canvas" onClick={()=>fit()}><Icon name="Maximize2"/></button></div></div><div className="hint">Space + drag to pan · Alt + scroll to zoom · ⌘K to find anything</div>
 {drawer&&<aside className="drawer open" ref={drawerRef} role="dialog" aria-label={{agent:"New agent",search:"Search",roles:"Agent roles",ensembles:"Ensembles",collections:"Note collections",settings:"Settings & shortcuts",routines:"Routines",floor:"New isolated floor","floor-review":"Review floor",actions:"Node actions",arrange:"Arrange selection",group:"Rename group"}[drawer]??drawer}><header><h2>{{agent:"New agent",search:"Search anything",roles:"Agent roles",ensembles:"Ensembles",collections:"Note collections",settings:"Settings & shortcuts",routines:"Routines",floor:"New isolated floor","floor-review":"Review floor",actions:"Node actions",arrange:"Arrange selection",group:"Rename group"}[drawer]??drawer}</h2><button onClick={close} aria-label="Close panel">×</button></header>
  {drawer==="search"&&<><input aria-label="Search canvas" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Agents, notes, workspaces…"/>{allItems.filter(i=>i.title.toLowerCase().includes(query.toLowerCase())).map(i=><button className="result" key={i.id} onClick={()=>{focus(i.id);close();}}>{i.title}<small>{i.kind}</small></button>)}{projects.filter(p=>p.name.toLowerCase().includes(query.toLowerCase())).map(p=><button key={p.id} onClick={()=>{setProject(p.id);close();}}>{p.name} · Workspace</button>)}{d.roles.filter(r=>r.name.toLowerCase().includes(query.toLowerCase())).map(r=><button key={r.id} onClick={()=>open("roles")}>{r.name} · Role</button>)}{d.ensembles.filter(r=>r.title.toLowerCase().includes(query.toLowerCase())).map(r=><button key={r.id} onClick={()=>open("ensembles")}>{r.title} · Ensemble</button>)}</>}
  {drawer==="actions"&&currentSelection.map(id=>{const item=items.find(i=>i.id===id);if(!item)return null;const p=presentation(d,id);return <div key={id}><h3>{item.title}</h3>{item.node&&<label>Name<input value={item.title} maxLength={240} onChange={e=>updateNode(id,{title:e.target.value})}/></label>}<label>Role<select value={p.roleId??""} onChange={e=>update(setPresentation(d,id,{roleId:e.target.value||null}))}><option value="">No role</option>{d.roles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><button onClick={()=>update(setPresentation(d,id,{locked:!p.locked}))}>{p.locked?"Unlock":"Lock"}</button><button onClick={()=>update(setPresentation(d,id,{blurred:!p.blurred}))}>{p.blurred?"Reveal contents":"Blur contents"}</button><button onClick={()=>{setLifted({id,dock:null});close();}}>Lift</button>{d.edges.filter(e=>e.source===id||e.target===id).map(edge=><button key={edge.id} onClick={()=>update({...d,edges:d.edges.filter(e=>e.id!==edge.id)})}>Disconnect {allItems.find(i=>i.id===(edge.source===id?edge.target:edge.source))?.title??"Unavailable node"}</button>)}{item.thread&&<><button onClick={()=>update(setPresentation(d,id,{face:d.presentations[id]?.face==="terminal"?"chat":"terminal"}))}>{d.presentations[id]?.face==="terminal"?"Show agent chat":"Show thread terminal"}</button><p className="dim">Role instructions apply to new agent sessions. Send them explicitly to update this conversation.</p><button onClick={()=>{const role=d.roles.find(r=>r.id===p.roleId);if(role)void sdk.threads.send({mode:"queue-if-active",threadId:id,input:[{type:"text",text:`Assigned role: ${role.name}\n${role.instructions}`,mentions:[]}]}).then(()=>setNotice("Role instructions sent.")).catch(e=>setNotice(String(e)));}} disabled={!p.roleId}>Send role instructions</button>{d.roles.find(r=>r.id===p.roleId)?.maestro&&<><button onClick={()=>{setRecruitParent(id);open("agent");}}>Recruit teammate</button><p>{snapshot.threads.filter(t=>t.parentThreadId===id).length} direct teammates</p>{snapshot.threads.filter(t=>t.parentThreadId===id).map(t=><button key={t.id} onClick={()=>{focus(t.id);close();}}>{t.title} · {stateNames[t.state]}</button>)}</>}<button className="danger" onClick={()=>void sdk.threads.stop({threadId:id}).then(()=>{refresh();setNotice("Stop requested. Check the agent status before continuing.");}).catch(e=>setNotice(String(e)))}>Stop agent</button></>}{item.node&&<button className="danger" onClick={()=>{deleteSelection();close();}}>Delete node</button>}</div>;})}
  {drawer==="arrange"&&[["left","Align left"],["center-x","Center horizontally"],["right","Align right"],["top","Align top"],["center-y","Center vertically"],["bottom","Align bottom"],["distribute-x","Distribute horizontally"],["distribute-y","Distribute vertically"],["tidy","Tidy into grid"]].map(([mode,label])=><button key={mode} onClick={()=>update(arrange(d,currentSelection,boxes,mode as Arrangement))}>{label}</button>)}
  {drawer==="group"&&d.groups.filter(g=>g.members.some(id=>currentSelection.includes(id))).map(g=><label key={g.id}>Group name<input value={g.title} maxLength={240} onChange={e=>update({...d,groups:d.groups.map(v=>v.id===g.id?{...v,title:e.target.value}:v)})}/><button onClick={()=>update(ungroupNodes(d,g.members))}>Ungroup</button></label>)}
  {drawer==="roles"&&<><button onClick={()=>update({...d,roles:[...d.roles,{id:newId(),name:"New role",color:"#578af3",instructions:"",maestro:false}]})}>+ Create role</button>{d.roles.map(r=><section className="library-card" key={r.id}><label>Name<input value={r.name} maxLength={120} onChange={e=>{if(e.target.value)update({...d,roles:d.roles.map(v=>v.id===r.id?{...v,name:e.target.value}:v)});}}/></label><label>Badge color<input type="color" value={r.color} onChange={e=>update({...d,roles:d.roles.map(v=>v.id===r.id?{...v,color:e.target.value}:v)})}/></label><label>Instructions<textarea value={r.instructions} maxLength={30000} onChange={e=>update({...d,roles:d.roles.map(v=>v.id===r.id?{...v,instructions:e.target.value}:v)})}/></label><label className="check"><input type="checkbox" checked={r.maestro} onChange={e=>update({...d,roles:d.roles.map(v=>v.id===r.id?{...v,maestro:e.target.checked}:v)})}/>Maestro role</label><button onClick={()=>update({...d,roles:d.roles.filter(v=>v.id!==r.id),nodes:d.nodes.map(n=>n.roleId===r.id?{...n,roleId:null}:n),presentations:Object.fromEntries(Object.entries(d.presentations).map(([id,p])=>[id,p.roleId===r.id?{...p,roleId:null}:p]))})}>Delete role</button></section>)}</>}
  {drawer==="ensembles"&&<><button onClick={()=>downloadData(exportLibrary(d,"ensembles",d.ensembles),"agent-canvas-ensembles.json")}>Export all ensembles</button><label>Import library<input type="file" accept="application/json,.json" onChange={e=>{const f=e.target.files?.[0];if(f)void importLibraryFile(f);}}/></label><input aria-label="Search ensembles" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search ensembles"/>{!d.ensembles.length&&<p>Select nodes and choose Save ensemble to capture their layout and connections.</p>}{d.ensembles.filter(e=>e.title.toLowerCase().includes(query.toLowerCase())).map(e=><section className="library-card" key={e.id}><input aria-label="Ensemble name" value={e.title} maxLength={240} onChange={v=>{if(v.target.value)update({...d,ensembles:d.ensembles.map(x=>x.id===e.id?{...x,title:v.target.value}:x)});}}/><p>{e.nodes.length} nodes · {e.edges.length} connections</p><button onClick={()=>{const r=placeEnsemble(d,e,workspaceId,environment,viewport.x+80,viewport.y+100);update(r.document);setSelection(r.ids);close();}}>Place on this canvas</button><button onClick={()=>downloadData(exportLibrary(d,"ensembles",[e]),"agent-canvas-ensemble.json")}>Export ensemble</button><button onClick={()=>update({...d,ensembles:d.ensembles.filter(x=>x.id!==e.id)})}>Delete ensemble</button></section>)}</>}
  {drawer==="collections"&&<><input aria-label="Search note collections" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search collections"/><button onClick={()=>downloadData(exportLibrary(d,"collections",d.collectionTemplates),"agent-canvas-note-library.json")}>Export saved note templates</button><label>Import note library<input type="file" accept="application/json,.json" onChange={e=>{const f=e.target.files?.[0];if(f)void importLibraryFile(f);}}/></label><button onClick={()=>{const members=currentSelection.filter(id=>d.nodes.some(n=>n.id===id&&n.kind==="note"));update({...d,collections:[...d.collections,{id:newId(),title:`Collection ${d.collections.length+1}`,members}]});}}>+ Collect selected notes</button>{d.collections.filter(c=>c.title.toLowerCase().includes(query.toLowerCase())).map(c=><section className="library-card" key={c.id}><input aria-label="Collection name" value={c.title} maxLength={240} onChange={e=>{if(e.target.value)update({...d,collections:d.collections.map(v=>v.id===c.id?{...v,title:e.target.value}:v)});}}/>{c.members.map(id=><button key={id} onClick={()=>{focus(id);close();}}>{d.nodes.find(n=>n.id===id)?.title}</button>)}<button onClick={()=>{const e=extractEnsemble(d,c.members,boxes);e.title=c.title;update({...d,collectionTemplates:[...d.collectionTemplates,e]});}}>Save as reusable collection</button><button onClick={()=>{const e=extractEnsemble(d,c.members,boxes);e.title=c.title;downloadData(exportLibrary(d,"collections",[e]),"agent-canvas-collection.json");}}>Export collection</button><button onClick={()=>update({...d,collections:d.collections.filter(v=>v.id!==c.id)})}>Delete collection</button></section>)}<h3>Reusable note collections</h3>{d.collectionTemplates.filter(t=>t.title.toLowerCase().includes(query.toLowerCase())).map(t=><section key={t.id} className="library-card"><input aria-label="Note template name" value={t.title} maxLength={240} onChange={e=>{if(e.target.value)update({...d,collectionTemplates:d.collectionTemplates.map(v=>v.id===t.id?{...v,title:e.target.value}:v)});}}/><p>{t.nodes.length} notes</p><button onClick={()=>{const result=placeCollection(d,t,workspaceId,environment,viewport.x+80,viewport.y+100);update(result.document);setSelection(result.ids);close();}}>Place on this canvas</button><button onClick={()=>downloadData(exportLibrary(d,"collections",[t]),"agent-canvas-collection.json")}>Export template</button><button onClick={()=>update({...d,collectionTemplates:d.collectionTemplates.filter(v=>v.id!==t.id)})}>Delete template</button></section>)}</>}
  {drawer==="settings"&&<><label className="check"><input type="checkbox" checked={d.settings.grid} onChange={e=>update({...d,settings:{...d.settings,grid:e.target.checked}})}/>Snap to 20-unit grid</label>{[["nodeWidth","Agent width",320,1500],["nodeHeight","Agent height",260,1500],["noteWidth","Note width",120,1000],["noteHeight","Note height",80,1000]].map(([key,label,min,max])=><label key={key}>{label}<input type="number" min={min} max={max} step="20" value={d.settings[key as "nodeWidth"]} onChange={e=>{const v=Number(e.target.value);if(v>=Number(min)&&v<=Number(max))update({...d,settings:{...d.settings,[key]:snap(v)}});}}/></label>)}<button onClick={download}>Export canvas backup</button><button onClick={()=>void reloadShared()}>Reload shared canvas (backs up local draft)</button><label>Import canvas<input type="file" accept="application/json,.json" onChange={e=>{const f=e.target.files?.[0];if(f)void importFile(f);}}/></label><button disabled={!history.past.length} onClick={()=>setHistory(undo)}>Undo</button><button disabled={!history.future.length} onClick={()=>setHistory(redo)}>Redo</button><h3>Shortcuts</h3><p>⌘K Search · ⌘G Group · ⇧⌘G Ungroup<br/>⌘Z Undo · ⇧⌘Z Redo · ⌘C / ⌘V Copy/paste<br/>⌘⌥← / → Traverse connections<br/>⇧⌘A Next agent needing attention<br/>⇧⌘M Minimap · ⇧⌘T Tidy<br/>⌘\ Focus selection · 0 Fit all<br/>Space + drag Pan · Alt + scroll Zoom</p></>}
  {drawer==="routines"&&<Routines key={workspaceId} projectId={workspaceId} threads={snapshot.threads}/>}
  {drawer==="floor-review"&&environment&&<FloorReview environmentId={environment} onOpenThread={id=>navigate.toThread(id)} threadId={snapshot.threads.find(t=>t.environmentId===environment)?.id}/>}{(drawer==="agent"||drawer==="floor")&&<><label>Role<select value={agentRole} onChange={e=>setAgentRole(e.target.value)}><option value="">No role</option>{d.roles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><p className="dim">Choose the real BB provider, model and environment below. Sending creates and starts this agent.</p><NewThreadComposer defaultProjectId={workspaceId==="personal"?undefined:workspaceId} defaultEnvironment={drawer==="floor"?{type:"provider",environmentProviderId:"git-worktree",inputs:{branch:{kind:"default"}}}:environment?{type:"reuse",environmentId:environment}:undefined} initialPrompt={spawnTarget?.content||undefined} draftKey={`agent-canvas:new:${spawnTarget?.id??workspaceId}`} layout="document" onSubmit={async(request:NewThreadRequest)=>{if(drawer==="floor"&&!((request.environment.type==="host"&&request.environment.workspace.type==="managed-worktree")||(request.environment.type==="provider"&&request.environment.environmentProviderId==="git-worktree")))throw Error("Choose a new isolated worktree in the environment picker to create a floor.");const role=d.roles.find(r=>r.id===agentRole);const instructions=role?`Role: ${role.name}\n${role.instructions}\n\n`:"";const result=await sdk.threads.spawn({...request,...(recruitParent?{parentThreadId:recruitParent}:{}),input:instructions?[{type:"text",text:instructions,mentions:[]},...request.input]:request.input});const target=spawnTarget;update(v=>{let next=target?removeNodes(v,[target.id]):v;next=setPresentation(next,result.id,{roleId:role?.id??null,box:target?.box??{x:viewport.x+100,y:viewport.y+100,w:d.settings.nodeWidth,h:d.settings.nodeHeight}});if(target)for(const edge of v.edges.filter(e=>e.source===target.id||e.target===target.id))next=connect(next,edge.source===target.id?result.id:edge.source,edge.target===target.id?result.id:edge.target);return next;});refresh();close();}}/></>}
 </aside>}
 </section></div>;
}
function NativeChat({threadId}:{threadId:string}){const root=useRef<HTMLDivElement>(null),[visible,setVisible]=useState(false);useEffect(()=>{const observer=new IntersectionObserver(([e])=>setVisible(e.isIntersecting),{rootMargin:"160px"});if(root.current)observer.observe(root.current);return()=>observer.disconnect();},[]);return <div className="native-chat" ref={root}>{visible&&<ThreadChat threadId={threadId} variant="compact" layout="contained" permissionPolicy="inherit"/>}</div>;}
function NodeContent({node,update,onLaunch}:{node:CanvasNode;update:(patch:Partial<CanvasNode>)=>void;onLaunch:()=>void}){
 const [formatted,setFormatted]=useState(false),[stroke,setStroke]=useState<{x:number;y:number}[]|null>(null),[color,setColor]=useState("#578af3");const drawing=useRef<SVGSVGElement>(null);
 if(node.kind==="note"||node.kind==="text")return <div className={`note-body ${node.kind==="text"?"text-body":""}`}><div className="note-tools"><button onClick={()=>setFormatted(v=>!v)}>{formatted?"Edit":"Preview"}</button>{node.kind==="note"&&<input type="color" aria-label="Note color" value={node.color} onChange={e=>update({color:e.target.value})}/>}</div>{formatted?<div className="markdown"><Markdown content={node.content}/></div>:<textarea aria-label={`${node.title} content`} value={node.content} maxLength={200000} placeholder={node.kind==="note"?"Write shared context…":"Type your thinking…"} onChange={e=>update({content:e.target.value})}/>}</div>;
 if(node.kind==="drawing"){const p=(e:ReactPointerEvent)=>{const r=drawing.current!.getBoundingClientRect();return {x:(e.clientX-r.left)*node.box.w/r.width,y:(e.clientY-r.top)*(node.box.h-70)/r.height};};return <div className="drawing-body"><div className="note-tools"><input type="color" aria-label="Stroke color" value={color} onChange={e=>setColor(e.target.value)}/><button onClick={()=>update({strokes:node.strokes.slice(0,-1)})}>Undo stroke</button></div><svg ref={drawing} className="drawing-surface" viewBox={`0 0 ${node.box.w} ${node.box.h-70}`} onPointerDown={e=>{e.stopPropagation();e.currentTarget.setPointerCapture(e.pointerId);setStroke([p(e)]);}} onPointerMove={e=>{if(stroke&&stroke.length<2000)setStroke(s=>s?[...s,p(e)]:s);}} onPointerUp={()=>{if(stroke&&node.strokes.length<100)update({strokes:[...node.strokes,{points:stroke,color,width:3}]});setStroke(null);}} onPointerCancel={()=>setStroke(null)}>{[...node.strokes,...(stroke?[{points:stroke,color,width:3}]:[])].map((s,i)=><polyline key={i} points={s.points.map(p=>`${p.x},${p.y}`).join(" ")} stroke={s.color} strokeWidth={s.width} fill="none" strokeLinecap="round" strokeLinejoin="round"/>)}</svg></div>;}
 if(node.kind==="agent")return <div className="template-body"><Icon name="Terminal"/><p>This saved agent is a template.</p><textarea aria-label="Template prompt" value={node.content} onChange={e=>update({content:e.target.value})}/><button onClick={onLaunch}>Choose provider & launch</button></div>;
 if(node.kind==="portal")return <Portal node={node} onSave={url=>update({url})}/>;
 return <FileTree node={node}/>;
}

function FileTree({node}:{node:CanvasNode}){
 const rpc=useRpc<typeof rpcContract>();const [query,setQuery]=useState(""),[entries,setEntries]=useState<{path:string;name:string;kind:"file"|"directory"}[]>([]),[truncated,setTruncated]=useState(false),[error,setError]=useState(""),[busy,setBusy]=useState(false),[file,setFile]=useState<{path:string;content:string;sha256:string}|null>(null),[dirty,setDirty]=useState(false);
 useEffect(()=>{if(!node.environmentId)return;let cancelled=false;const timer=setTimeout(()=>{setBusy(true);void rpc.call("listFiles",{environmentId:node.environmentId!,query}).then(r=>{if(!cancelled){setEntries(r.paths);setTruncated(r.truncated);setError("");}}).catch(e=>{if(!cancelled)setError(e instanceof Error?e.message:"Files unavailable");}).finally(()=>{if(!cancelled)setBusy(false);});},200);return()=>{cancelled=true;clearTimeout(timer);};},[rpc,node.environmentId,query]);
 async function read(path:string){if(!node.environmentId)return;if(dirty){setError("Save the current draft before opening another file.");return;}setBusy(true);try{const value=await rpc.call("readFile",{environmentId:node.environmentId,path});setFile({path,...value});setError("");}catch(e){setError(e instanceof Error?e.message:"File unavailable");}finally{setBusy(false);}}
 async function save(){if(!file||!node.environmentId)return;setBusy(true);try{await rpc.call("writeFile",{environmentId:node.environmentId,path:file.path,content:file.content,sha256:file.sha256});setDirty(false);const value=await rpc.call("readFile",{environmentId:node.environmentId,path:file.path});setFile({...file,...value});setError("");}catch(e){setError(e instanceof Error?e.message:"Save failed; draft retained");}finally{setBusy(false);}}
 return <div className="file-tree"><div className="file-search"><input aria-label="Search files" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a file…"/>{busy&&<span>Loading…</span>}</div>{!node.environmentId&&<p>Select a floor before inserting a file tree.</p>}{error&&<p role="alert">{error}</p>}<div className="file-split"><nav aria-label="Environment files">{entries.map(entry=><button key={entry.path} onClick={()=>entry.kind==="directory"?setQuery(entry.path):void read(entry.path)}><Icon name={entry.kind==="directory"?"Folder":"File"}/>{entry.path}</button>)}{truncated&&<small>First 200 paths · refine your search</small>}</nav>{file&&<div className="file-editor"><div><span>{file.path}{dirty?" · unsaved":""}</span><button disabled={!dirty||busy} onClick={()=>void save()}>Save</button></div><textarea aria-label={`Edit ${file.path}`} value={file.content} maxLength={200000} onChange={e=>{setFile({...file,content:e.target.value});setDirty(true);}} spellCheck={false}/></div>}</div></div>;
}
