import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {call,ws} from './cdp.mjs';
const evaluate=async expression=>{const r=await call('Runtime.evaluate',{expression,returnByValue:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;};
const wait=()=>new Promise(r=>setTimeout(r,700));
const select=async(selector,value)=>{await evaluate(`(()=>{const el=document.querySelector(${JSON.stringify(selector)});el.value=${JSON.stringify(value)};el.dispatchEvent(new Event('change',{bubbles:true}));})()`);await wait();};
const click=async selector=>{await evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);await wait();};
const shot=async path=>{const s=await call('Page.captureScreenshot');await fs.writeFile(path,Buffer.from(s.data,'base64'));};
try {
 await call('Runtime.enable');
 assert.equal(await evaluate('location.origin'),'http://127.0.0.1:8769');
 await evaluate('localStorage.removeItem("fixture-shared-canvas");localStorage.removeItem("agent-canvas:document:v1")');await call('Page.reload');await new Promise(r=>setTimeout(r,2000));
 assert.equal(await evaluate('document.querySelector("[aria-label=\\\"Canvas workspace\\\"]").options[1].text'),'Canvas fixture');
 await select('[aria-label="Canvas workspace"]','fixture-project');
 assert.ok(await evaluate('[...document.querySelectorAll(".floor")].some(el=>el.textContent.includes("Feature floor"))'));
 await click('[aria-label="Agent"]');
 assert.equal(await evaluate('document.querySelector("[aria-label=\\\"Agent workspace\\\"]").value'),'fixture-project');
 assert.equal(await evaluate('document.querySelector(".agent-setup label:nth-child(2) select").options.length'),6);
 await evaluate('(()=>{const el=document.querySelector("[data-testid=bb-new-thread-composer-input]");Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,"value").set.call(el,"Implement the selected workspace task");el.dispatchEvent(new Event("input",{bubbles:true}));})()');
 await wait();
 const draftKey=await evaluate('document.querySelector("[data-testid=bb-new-thread-composer]").dataset.draftKey');
 await select('[aria-label="Agent workspace"]','second-project');
 assert.equal(await evaluate('document.querySelector("[data-testid=bb-new-thread-composer]").dataset.defaultProjectId'),'second-project');
 assert.equal(await evaluate('document.querySelector("[data-testid=bb-new-thread-composer]").dataset.defaultEnvironment'),'');
 assert.equal(await evaluate('document.querySelector("[data-testid=bb-new-thread-composer]").dataset.draftKey'),draftKey);
 assert.equal(await evaluate('document.querySelector("[data-testid=bb-new-thread-composer-input]").value'),'Implement the selected workspace task');
 const native=await evaluate('(()=>{const el=document.querySelector("[data-testid=bb-new-thread-composer-submit]"),style=getComputedStyle(el);return {display:style.display,width:el.getBoundingClientRect().width,container:el.parentElement.getBoundingClientRect().width,padding:style.padding};})()');
 assert.notEqual(native.display,'block');assert.ok(native.width<native.container/2,JSON.stringify(native));
 await fs.mkdir('docs/media',{recursive:true});
 await shot('docs/media/agent-canvas-agent-setup-desktop.png');
 await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:false});await wait();
 const bounds=await evaluate('(()=>{const el=document.querySelector(".agent-drawer"),r=el.getBoundingClientRect();return {left:r.left,right:r.right,width:innerWidth};})()');assert.ok(bounds.left>=0&&bounds.right<=bounds.width);
 await shot('docs/media/agent-canvas-agent-setup-mobile.png');
 await call('Emulation.clearDeviceMetricsOverride');await wait();
 await click('[data-testid="bb-new-thread-composer-submit"]');
 const request=await evaluate('window.lastSpawn');assert.equal(request.projectId,'second-project');assert.match(request.input[0].text,/Role: Engineer/);assert.equal(request.input[1].text,'Implement the selected workspace task');
 assert.equal(await evaluate('document.querySelector("[aria-label=\\\"Canvas workspace\\\"]").value'),'second-project');
 await evaluate('[...document.querySelectorAll(".sidebutton")].find(el=>el.textContent==="Agent roles").click()');await wait();
 assert.equal(await evaluate('document.querySelectorAll(".library-card textarea").length'),5);
 assert.ok(await evaluate('[...document.querySelectorAll(".library-card textarea")].every(el=>el.value.length>100)'));
 await shot('docs/media/agent-canvas-role-presets.png');
 console.log(JSON.stringify({passed:true,checks:['workspace labels and floors','five roles with instructions','workspace seeding and environment reset','draft preserved across workspace changes','native composer CSS isolation','desktop and mobile drawer bounds','submitted workspace and role instructions','created-agent workspace focus'],native}));
} finally {await call('Emulation.clearDeviceMetricsOverride').catch(()=>{});ws.close();}
